#ifndef FIRMUPS_DEVICE_SDK_ERROR_H
#define FIRMUPS_DEVICE_SDK_ERROR_H

enum firmups_sdk_error_code {
	FIRMUPS_SDK_ERROR_NONE = 0,
	FIRMUPS_SDK_ERROR_INVALID_ARGUMENT = 1,
	FIRMUPS_SDK_ERROR_BUFFER_TOO_SMALL = 2,
	FIRMUPS_SDK_ERROR_CRYPTOGRAPHIC_FAILURE = 3,
	FIRMUPS_SDK_ERROR_COMMUNICATION_FAILURE = 4,
	FIRMUPS_SDK_ERROR_UNEXPECTED_RESPONSE = 5,
	FIRMUPS_SDK_ERROR_TIMEOUT = 6,
	FIRMUPS_SDK_ERROR_NOT_INITIALIZED = 7,
	FIRMUPS_SDK_ERROR_ALREADY_INITIALIZED = 8,
	FIRMUPS_SDK_ERROR_UNSUPPORTED_OPERATION = 9,
	FIRMUPS_SDK_ERROR_OPERATION_ENCODING = 12,
	FIRMUPS_SDK_ERROR_OPERATION_PARSING = 13,
	FIRMUPS_SDK_ERROR_MESSAGE_ENCODING = 14,
	FIRMUPS_SDK_ERROR_MESSAGE_PARSING = 15,
	FIRMUPS_SDK_ERROR_UNSUPPORTED_CONCURRENCY = 16,
	FIRMUPS_SDK_ERROR_NOT_FOUND = 17,
	// Add more error codes as needed
};

#endif // FIRMUPS_DEVICE_SDK_ERROR_H
