if(NOT DEFINED FIRMUPS_ASCON_IMPL)
    set(FIRMUPS_ASCON_IMPL ref)
endif()
if(DEFINED FIRMUPS_USE_AES AND NOT DEFINED FIRMUPS_USE_CRYPTO_CALLBACKS)
    message(FATAL_ERROR "FIRMUPS_USE_AES is defined but FIRMUPS_USE_CRYPTO_CALLBACKS is not defined. FIRMUPS_USE_AES requires FIRMUPS_USE_CRYPTO_CALLBACKS to be defined.")
endif()

macro(configure_firmups_sdk target)
    if(DEFINED FIRMUPS_USE_AES)
        target_compile_definitions(${target} PRIVATE FIRMUPS_USE_AES)
    endif()
    if(DEFINED FIRMUPS_USE_CRYPTO_CALLBACKS)
        target_compile_definitions(${target} PRIVATE FIRMUPS_USE_CRYPTO_CALLBACKS)
    endif()
endmacro()